import { ViewStyle } from "react-native";
declare const Fill: ViewStyle;
declare const PaddingNone: ViewStyle;
declare const Padding3: ViewStyle;
declare const Padding6: ViewStyle;
declare const PaddingX: (x: number) => ViewStyle;
declare const MarginNone: ViewStyle;
declare const Margin3: ViewStyle;
declare const Margin6: ViewStyle;
declare const MarginX: (x: number) => ViewStyle;
export { Fill, PaddingNone, Padding3, Padding6, PaddingX, MarginNone, Margin3, Margin6, MarginX, };
