import { ViewStyle } from "react-native";
declare const Fill: ViewStyle;
declare const Center: ViewStyle;
declare const RowCenter: ViewStyle;
declare const ColumnCenter: ViewStyle;
declare const Opacity0: ViewStyle;
declare const Opacity: (number: number) => ViewStyle;
declare const Height: (x: number) => ViewStyle;
declare const Width: (x: number) => ViewStyle;
declare const BgColor: (x: string) => ViewStyle;
declare const PaddingNone: ViewStyle;
declare const Padding3: ViewStyle;
declare const Padding6: ViewStyle;
declare const PaddingX: (x: number) => ViewStyle;
declare const PaddingVerticalX: (x: number) => ViewStyle;
declare const PaddingHorizontalX: (x: number) => ViewStyle;
declare const MarginNone: ViewStyle;
declare const Margin3: ViewStyle;
declare const Margin6: ViewStyle;
declare const MarginX: (x: number) => ViewStyle;
declare const Shape30x30: ViewStyle;
declare const ShapeNxN: (x: number, y: number) => ViewStyle;
declare const BorderRadius: (x: number) => ViewStyle;
export { Fill, Center, RowCenter, ColumnCenter, Opacity, Height, Width, Opacity0, BgColor, PaddingNone, Padding3, Padding6, PaddingX, PaddingHorizontalX, PaddingVerticalX, MarginNone, Margin3, Margin6, MarginX, Shape30x30, ShapeNxN, BorderRadius, };
